version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  
  blazor:
    restart: on-failure
    build: ./Blazor
    container_name: 'blazor'
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

  api:
    restart: on-failure
    build: ./API
    container_name: 'api'
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
      - DATABASE_CONNECTION_STRING=Host=database;Port=5432;Database=your_database_name;User Id=your_username;Password=your_password
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - graphdb
      - rabbitmq
    networks:
      - rabbitmq_go_net

  graphdb:
    build: ./neo4js
    container_name: 'database'
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    networks:
      - rabbitmq_go_net
  
  gpt4all:
    image: gpt4all
    build: ./gpt4all
    ports:
      - "5000:5000"
    environment:
      - DISPLAY=${DISPLAY}
      - PATH=${PATH}="/root/gpt4all/bin/chat:/gpt4all/bin/chat"
      - XDG_RUNTIME_DIR=/tmp/xdg_runtime_dir
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data/local/share/nomic.ai:/home/user/.local/share/nomic.ai/GPT4All
      - ./data/gpt4all:/gpt4all
    networks:
      - rabbitmq_go_net
    network_mode: host

networks:
  rabbitmq_go_net:
    driver: bridge